version: 0.2
env:
  parameter-store:
    AWS_SECERET_KEY: /CodeBuild/AWS_SECERET_KEY
    AWS_KEY: /CodeBuild/AWS_KEY
phases:
  install:
    runtime-versions:
      nodejs: 8
  build:
    commands:
      - npm install -g serverless
      - sls config credentials --provider aws --key $AWS_KEY --secret $AWS_SECERET_KEY
      - serverless deploy
